import './globals.css'
import {Inter} from 'next/font/google'
import Header from "@/widgets/layout/Header";
import {clsx} from "clsx";
import {ReactNode} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <script async src="https://telegram.org/js/telegram-web-app.js"></script>
        <body className={clsx(inter.className, 'flex flex-col min-h-screen ')}>
        <Header/>
        <main className="flex flex-col grow">
            {children}
        </main>
        </body>
        </html>
    )
}
